name: detekt

on:
  push:
    branches: [ master ]

 jobs:
   detekt:
     runs-on: ubuntu-latest

     steps:
       - name: "checkout"
         uses: actions/checkout@v3

       - name: Detekt all
         uses: natiginfo/action-detekt-all@1.22.0
